version: '3.4'

services:
  avidev.filestream:
    image: ${DOCKER_REGISTRY-}avidevfilestream
    build:
      context: .
      dockerfile: AviDev.FileStream/Dockerfile
    container_name: avidevfilestream
    networks:
      - backend
    ports:
      - 50045:80

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres_filestream
    ports:
      - "5434:5432"
    restart: always
    volumes:
     - ./postgres-data:/var/lib/postgresql/data 
    networks:
      - backend

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com.br"
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/postgresql/data
    ports:
      - 8003:80
    restart: always
    networks:
      - backend

networks:
    backend:
        driver: bridge